[phases.setup]
nixPkgs = ["...", "python310"]

[phases.install]
cmd = "pip install -r requirements.txt"

[start]
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT --workers 4 --timeout 120"

[variables]
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"
PORT = "7860"

[healthcheck]
path = "/api/v1/health"
timeout = 100
